send_weekly_activity_report:
  cron: '0 10 * * MON'
  class: WeeklyActivityMailerJob
  queue: default
  description: 'This job sends weekly report to employees every Monday 10:00 AM'

send_daily_tech_nugget:
  cron: '0 10 * * 1-5'
  class: DailyTechNuggetMailerJob
  queue: default
  description: 'This job sends a daily tech nugget to employees Monday to Friday 10:00 AM'

reset_unread_tech_nugget:
  cron: '0 10 * * MON'
  class: WeeklyNuggetResetMailerJob
  queue: default
  description: 'This job resets unread tech nuggets older than 7 days every Monday 10:00 AM'

delete_timesheets_after_x_days:
  cron: '0 0 * * *'
  class: DeleteTimesheets
  queue: default
  description: 'This job deletes old timesheets as per preferences. This runs daily at midnight'

delete_deactivated_users_after_x_days:
  cron: '0 0 * * *'
  class: DeleteDeactivatedUsers
  queue: default
  description: 'This job deletes deactivated users as per preferences. This runs daily at midnight'

delete_archived_projects_after_x_days:
  cron: '0 0 * * *'
  class: DeleteArchivedProjects
  queue: default
  description: 'This job archived projects users as per preferences. This runs daily at midnight'
